#!/usr/bin/env expect

set TARGET [lindex $argv 0]

spawn nmap -v -p80 -sC -sV -oA nmap-tcp-all-ports $TARGET

expect {
    "*open*http*" {
        set result "$expect_out(0,string)"
    	system "echo $result"
    }
}

interact

